train_datasets: [imagenet]
batch_size: 512
label_fractions: [1.0]
num_epochs: [90]
lr: [0.2]
weight_decay: [0]
num_workers: 40
prefetch_factor: 2
pin_memory: False # Set to True if you have enough memory. Larger datasets will not benefit from this
use_checkpoint: True # Recommended for memory efficiency
use_val_subset: False # Set to True if you want to test hyperparameters on a validation subset
