output_path: /home/luan/Desktop/simclr_output/train_encoder_cifar100
datasets_path: /home/luan/Desktop/datasets
train_datasets: [cifar100]
batch_size: 32
num_epochs: 100
num_workers: 8
model: resnet50
transform_resize: [224, 224]
val_percent: 0.1
projection_head_mode: non-linear # linear, non-linear or none
temperature: 0.5
