output_path: /disk0/lmk22/simclr_output/train_encoder_cifar10
datasets_path: /disk0/lmk22/datasets
train_datasets: [cifar10]
batch_size: 4096 # Paper uses 4096
chunk_size: 128 # Number of samples to infer at the same time (divide batch size)
num_epochs: 100 # The paper uses 100 epochs
num_workers: 64
model: resnet50
transform_resize: [224, 224]
projection_head_mode: non-linear # linear, non-linear or none
temperature: 0.5 # The paper tells us that the optimal and stable temperature is 0.5
projection_dim: 128 # The paper defines the latent space of size 128
warmup_epochs: 10 # The paper uses 10 epochs to warm up the learning rate
