encoder_config: configs/train_encoder_imagenet.yaml
train_datasets: [imagenet]
batch_size: 4096 # B.6. Defines batch size as 4096
label_fractions: [0.01, 0.1, 1.0]
num_epochs: [60, 30, 10] # B.6. Defines the number of epochs for 1%, 10%
lr: [0.002, 0.002, 0.002]
weight_decay: [0.000001, 0.000001, 0.000001]
