encoder_config: configs/train_encoder_imagenet.yaml
train_datasets: [cifar100]
batch_size: 256
label_fractions: [0.01, 0.1, 1.0]
num_epochs: [60, 30, 10]
lr: [0.001, 0.001, 0.001]
weight_decay: [0.000001, 0.000001, 0.000001]
